// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 10000_C2SRobotLoginReq.proto

#ifndef PROTOBUF_10000_5fC2SRobotLoginReq_2eproto__INCLUDED
#define PROTOBUF_10000_5fC2SRobotLoginReq_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_10000_5fC2SRobotLoginReq_2eproto();
void protobuf_AssignDesc_10000_5fC2SRobotLoginReq_2eproto();
void protobuf_ShutdownFile_10000_5fC2SRobotLoginReq_2eproto();

class C2SRobotLoginReq;

// ===================================================================

class C2SRobotLoginReq : public ::google::protobuf::Message {
 public:
  C2SRobotLoginReq();
  virtual ~C2SRobotLoginReq();

  C2SRobotLoginReq(const C2SRobotLoginReq& from);

  inline C2SRobotLoginReq& operator=(const C2SRobotLoginReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const C2SRobotLoginReq& default_instance();

  void Swap(C2SRobotLoginReq* other);

  // implements Message ----------------------------------------------

  C2SRobotLoginReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const C2SRobotLoginReq& from);
  void MergeFrom(const C2SRobotLoginReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string verify_key = 1;
  inline bool has_verify_key() const;
  inline void clear_verify_key();
  static const int kVerifyKeyFieldNumber = 1;
  inline const ::std::string& verify_key() const;
  inline void set_verify_key(const ::std::string& value);
  inline void set_verify_key(const char* value);
  inline void set_verify_key(const char* value, size_t size);
  inline ::std::string* mutable_verify_key();
  inline ::std::string* release_verify_key();
  inline void set_allocated_verify_key(::std::string* verify_key);

  // @@protoc_insertion_point(class_scope:Protocol.C2SRobotLoginReq)
 private:
  inline void set_has_verify_key();
  inline void clear_has_verify_key();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* verify_key_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_10000_5fC2SRobotLoginReq_2eproto();
  friend void protobuf_AssignDesc_10000_5fC2SRobotLoginReq_2eproto();
  friend void protobuf_ShutdownFile_10000_5fC2SRobotLoginReq_2eproto();

  void InitAsDefaultInstance();
  static C2SRobotLoginReq* default_instance_;
};
// ===================================================================


// ===================================================================

// C2SRobotLoginReq

// required string verify_key = 1;
inline bool C2SRobotLoginReq::has_verify_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void C2SRobotLoginReq::set_has_verify_key() {
  _has_bits_[0] |= 0x00000001u;
}
inline void C2SRobotLoginReq::clear_has_verify_key() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void C2SRobotLoginReq::clear_verify_key() {
  if (verify_key_ != &::google::protobuf::internal::kEmptyString) {
    verify_key_->clear();
  }
  clear_has_verify_key();
}
inline const ::std::string& C2SRobotLoginReq::verify_key() const {
  return *verify_key_;
}
inline void C2SRobotLoginReq::set_verify_key(const ::std::string& value) {
  set_has_verify_key();
  if (verify_key_ == &::google::protobuf::internal::kEmptyString) {
    verify_key_ = new ::std::string;
  }
  verify_key_->assign(value);
}
inline void C2SRobotLoginReq::set_verify_key(const char* value) {
  set_has_verify_key();
  if (verify_key_ == &::google::protobuf::internal::kEmptyString) {
    verify_key_ = new ::std::string;
  }
  verify_key_->assign(value);
}
inline void C2SRobotLoginReq::set_verify_key(const char* value, size_t size) {
  set_has_verify_key();
  if (verify_key_ == &::google::protobuf::internal::kEmptyString) {
    verify_key_ = new ::std::string;
  }
  verify_key_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* C2SRobotLoginReq::mutable_verify_key() {
  set_has_verify_key();
  if (verify_key_ == &::google::protobuf::internal::kEmptyString) {
    verify_key_ = new ::std::string;
  }
  return verify_key_;
}
inline ::std::string* C2SRobotLoginReq::release_verify_key() {
  clear_has_verify_key();
  if (verify_key_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = verify_key_;
    verify_key_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void C2SRobotLoginReq::set_allocated_verify_key(::std::string* verify_key) {
  if (verify_key_ != &::google::protobuf::internal::kEmptyString) {
    delete verify_key_;
  }
  if (verify_key) {
    set_has_verify_key();
    verify_key_ = verify_key;
  } else {
    clear_has_verify_key();
    verify_key_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_10000_5fC2SRobotLoginReq_2eproto__INCLUDED
