// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 10001_S2CRobotLoginRsp.proto

#ifndef PROTOBUF_10001_5fS2CRobotLoginRsp_2eproto__INCLUDED
#define PROTOBUF_10001_5fS2CRobotLoginRsp_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_10001_5fS2CRobotLoginRsp_2eproto();
void protobuf_AssignDesc_10001_5fS2CRobotLoginRsp_2eproto();
void protobuf_ShutdownFile_10001_5fS2CRobotLoginRsp_2eproto();

class S2CRobotLoginRsp;

// ===================================================================

class S2CRobotLoginRsp : public ::google::protobuf::Message {
 public:
  S2CRobotLoginRsp();
  virtual ~S2CRobotLoginRsp();

  S2CRobotLoginRsp(const S2CRobotLoginRsp& from);

  inline S2CRobotLoginRsp& operator=(const S2CRobotLoginRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CRobotLoginRsp& default_instance();

  void Swap(S2CRobotLoginRsp* other);

  // implements Message ----------------------------------------------

  S2CRobotLoginRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CRobotLoginRsp& from);
  void MergeFrom(const S2CRobotLoginRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool login_result = 1;
  inline bool has_login_result() const;
  inline void clear_login_result();
  static const int kLoginResultFieldNumber = 1;
  inline bool login_result() const;
  inline void set_login_result(bool value);

  // @@protoc_insertion_point(class_scope:Protocol.S2CRobotLoginRsp)
 private:
  inline void set_has_login_result();
  inline void clear_has_login_result();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  bool login_result_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_10001_5fS2CRobotLoginRsp_2eproto();
  friend void protobuf_AssignDesc_10001_5fS2CRobotLoginRsp_2eproto();
  friend void protobuf_ShutdownFile_10001_5fS2CRobotLoginRsp_2eproto();

  void InitAsDefaultInstance();
  static S2CRobotLoginRsp* default_instance_;
};
// ===================================================================


// ===================================================================

// S2CRobotLoginRsp

// required bool login_result = 1;
inline bool S2CRobotLoginRsp::has_login_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2CRobotLoginRsp::set_has_login_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2CRobotLoginRsp::clear_has_login_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2CRobotLoginRsp::clear_login_result() {
  login_result_ = false;
  clear_has_login_result();
}
inline bool S2CRobotLoginRsp::login_result() const {
  return login_result_;
}
inline void S2CRobotLoginRsp::set_login_result(bool value) {
  set_has_login_result();
  login_result_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_10001_5fS2CRobotLoginRsp_2eproto__INCLUDED
