// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 20002_C2SQQLoginCaptchaConfirm.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "20002_C2SQQLoginCaptchaConfirm.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

namespace {

const ::google::protobuf::Descriptor* C2SQQLoginCaptchaConfirm_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  C2SQQLoginCaptchaConfirm_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_20002_5fC2SQQLoginCaptchaConfirm_2eproto() {
  protobuf_AddDesc_20002_5fC2SQQLoginCaptchaConfirm_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "20002_C2SQQLoginCaptchaConfirm.proto");
  GOOGLE_CHECK(file != NULL);
  C2SQQLoginCaptchaConfirm_descriptor_ = file->message_type(0);
  static const int C2SQQLoginCaptchaConfirm_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C2SQQLoginCaptchaConfirm, captcha_code_),
  };
  C2SQQLoginCaptchaConfirm_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      C2SQQLoginCaptchaConfirm_descriptor_,
      C2SQQLoginCaptchaConfirm::default_instance_,
      C2SQQLoginCaptchaConfirm_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C2SQQLoginCaptchaConfirm, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C2SQQLoginCaptchaConfirm, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(C2SQQLoginCaptchaConfirm));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_20002_5fC2SQQLoginCaptchaConfirm_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    C2SQQLoginCaptchaConfirm_descriptor_, &C2SQQLoginCaptchaConfirm::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_20002_5fC2SQQLoginCaptchaConfirm_2eproto() {
  delete C2SQQLoginCaptchaConfirm::default_instance_;
  delete C2SQQLoginCaptchaConfirm_reflection_;
}

void protobuf_AddDesc_20002_5fC2SQQLoginCaptchaConfirm_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n$20002_C2SQQLoginCaptchaConfirm.proto\022\010"
    "Protocol\"0\n\030C2SQQLoginCaptchaConfirm\022\024\n\014"
    "captcha_code\030\001 \002(\t", 98);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "20002_C2SQQLoginCaptchaConfirm.proto", &protobuf_RegisterTypes);
  C2SQQLoginCaptchaConfirm::default_instance_ = new C2SQQLoginCaptchaConfirm();
  C2SQQLoginCaptchaConfirm::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_20002_5fC2SQQLoginCaptchaConfirm_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_20002_5fC2SQQLoginCaptchaConfirm_2eproto {
  StaticDescriptorInitializer_20002_5fC2SQQLoginCaptchaConfirm_2eproto() {
    protobuf_AddDesc_20002_5fC2SQQLoginCaptchaConfirm_2eproto();
  }
} static_descriptor_initializer_20002_5fC2SQQLoginCaptchaConfirm_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int C2SQQLoginCaptchaConfirm::kCaptchaCodeFieldNumber;
#endif  // !_MSC_VER

C2SQQLoginCaptchaConfirm::C2SQQLoginCaptchaConfirm()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void C2SQQLoginCaptchaConfirm::InitAsDefaultInstance() {
}

C2SQQLoginCaptchaConfirm::C2SQQLoginCaptchaConfirm(const C2SQQLoginCaptchaConfirm& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void C2SQQLoginCaptchaConfirm::SharedCtor() {
  _cached_size_ = 0;
  captcha_code_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

C2SQQLoginCaptchaConfirm::~C2SQQLoginCaptchaConfirm() {
  SharedDtor();
}

void C2SQQLoginCaptchaConfirm::SharedDtor() {
  if (captcha_code_ != &::google::protobuf::internal::kEmptyString) {
    delete captcha_code_;
  }
  if (this != default_instance_) {
  }
}

void C2SQQLoginCaptchaConfirm::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* C2SQQLoginCaptchaConfirm::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return C2SQQLoginCaptchaConfirm_descriptor_;
}

const C2SQQLoginCaptchaConfirm& C2SQQLoginCaptchaConfirm::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_20002_5fC2SQQLoginCaptchaConfirm_2eproto();
  return *default_instance_;
}

C2SQQLoginCaptchaConfirm* C2SQQLoginCaptchaConfirm::default_instance_ = NULL;

C2SQQLoginCaptchaConfirm* C2SQQLoginCaptchaConfirm::New() const {
  return new C2SQQLoginCaptchaConfirm;
}

void C2SQQLoginCaptchaConfirm::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_captcha_code()) {
      if (captcha_code_ != &::google::protobuf::internal::kEmptyString) {
        captcha_code_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool C2SQQLoginCaptchaConfirm::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string captcha_code = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_captcha_code()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->captcha_code().data(), this->captcha_code().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void C2SQQLoginCaptchaConfirm::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string captcha_code = 1;
  if (has_captcha_code()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->captcha_code().data(), this->captcha_code().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->captcha_code(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* C2SQQLoginCaptchaConfirm::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string captcha_code = 1;
  if (has_captcha_code()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->captcha_code().data(), this->captcha_code().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->captcha_code(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int C2SQQLoginCaptchaConfirm::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string captcha_code = 1;
    if (has_captcha_code()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->captcha_code());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void C2SQQLoginCaptchaConfirm::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const C2SQQLoginCaptchaConfirm* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const C2SQQLoginCaptchaConfirm*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void C2SQQLoginCaptchaConfirm::MergeFrom(const C2SQQLoginCaptchaConfirm& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_captcha_code()) {
      set_captcha_code(from.captcha_code());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void C2SQQLoginCaptchaConfirm::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void C2SQQLoginCaptchaConfirm::CopyFrom(const C2SQQLoginCaptchaConfirm& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C2SQQLoginCaptchaConfirm::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void C2SQQLoginCaptchaConfirm::Swap(C2SQQLoginCaptchaConfirm* other) {
  if (other != this) {
    std::swap(captcha_code_, other->captcha_code_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata C2SQQLoginCaptchaConfirm::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = C2SQQLoginCaptchaConfirm_descriptor_;
  metadata.reflection = C2SQQLoginCaptchaConfirm_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)
