// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageBase.proto

#ifndef PROTOBUF_MessageBase_2eproto__INCLUDED
#define PROTOBUF_MessageBase_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageBase_2eproto();
void protobuf_AssignDesc_MessageBase_2eproto();
void protobuf_ShutdownFile_MessageBase_2eproto();

class MessageBase;

// ===================================================================

class MessageBase : public ::google::protobuf::Message {
 public:
  MessageBase();
  virtual ~MessageBase();

  MessageBase(const MessageBase& from);

  inline MessageBase& operator=(const MessageBase& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageBase& default_instance();

  void Swap(MessageBase* other);

  // implements Message ----------------------------------------------

  MessageBase* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageBase& from);
  void MergeFrom(const MessageBase& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 len = 1;
  inline bool has_len() const;
  inline void clear_len();
  static const int kLenFieldNumber = 1;
  inline ::google::protobuf::uint32 len() const;
  inline void set_len(::google::protobuf::uint32 value);

  // required int32 opcode = 2;
  inline bool has_opcode() const;
  inline void clear_opcode();
  static const int kOpcodeFieldNumber = 2;
  inline ::google::protobuf::int32 opcode() const;
  inline void set_opcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Protocol.MessageBase)
 private:
  inline void set_has_len();
  inline void clear_has_len();
  inline void set_has_opcode();
  inline void clear_has_opcode();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 len_;
  ::google::protobuf::int32 opcode_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_MessageBase_2eproto();
  friend void protobuf_AssignDesc_MessageBase_2eproto();
  friend void protobuf_ShutdownFile_MessageBase_2eproto();

  void InitAsDefaultInstance();
  static MessageBase* default_instance_;
};
// ===================================================================


// ===================================================================

// MessageBase

// required uint32 len = 1;
inline bool MessageBase::has_len() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageBase::set_has_len() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageBase::clear_has_len() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageBase::clear_len() {
  len_ = 0u;
  clear_has_len();
}
inline ::google::protobuf::uint32 MessageBase::len() const {
  return len_;
}
inline void MessageBase::set_len(::google::protobuf::uint32 value) {
  set_has_len();
  len_ = value;
}

// required int32 opcode = 2;
inline bool MessageBase::has_opcode() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageBase::set_has_opcode() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageBase::clear_has_opcode() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageBase::clear_opcode() {
  opcode_ = 0;
  clear_has_opcode();
}
inline ::google::protobuf::int32 MessageBase::opcode() const {
  return opcode_;
}
inline void MessageBase::set_opcode(::google::protobuf::int32 value) {
  set_has_opcode();
  opcode_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageBase_2eproto__INCLUDED
