// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QQLoginCaptchaConfirm.proto

#ifndef PROTOBUF_QQLoginCaptchaConfirm_2eproto__INCLUDED
#define PROTOBUF_QQLoginCaptchaConfirm_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "MessageBase.pb.h"
// @@protoc_insertion_point(includes)

namespace Protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_QQLoginCaptchaConfirm_2eproto();
void protobuf_AssignDesc_QQLoginCaptchaConfirm_2eproto();
void protobuf_ShutdownFile_QQLoginCaptchaConfirm_2eproto();

class QQLoginCaptchaConfirm;

// ===================================================================

class QQLoginCaptchaConfirm : public ::google::protobuf::Message {
 public:
  QQLoginCaptchaConfirm();
  virtual ~QQLoginCaptchaConfirm();

  QQLoginCaptchaConfirm(const QQLoginCaptchaConfirm& from);

  inline QQLoginCaptchaConfirm& operator=(const QQLoginCaptchaConfirm& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const QQLoginCaptchaConfirm& default_instance();

  void Swap(QQLoginCaptchaConfirm* other);

  // implements Message ----------------------------------------------

  QQLoginCaptchaConfirm* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const QQLoginCaptchaConfirm& from);
  void MergeFrom(const QQLoginCaptchaConfirm& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string captcha_code = 1;
  inline bool has_captcha_code() const;
  inline void clear_captcha_code();
  static const int kCaptchaCodeFieldNumber = 1;
  inline const ::std::string& captcha_code() const;
  inline void set_captcha_code(const ::std::string& value);
  inline void set_captcha_code(const char* value);
  inline void set_captcha_code(const char* value, size_t size);
  inline ::std::string* mutable_captcha_code();
  inline ::std::string* release_captcha_code();
  inline void set_allocated_captcha_code(::std::string* captcha_code);

  // @@protoc_insertion_point(class_scope:Protocol.QQLoginCaptchaConfirm)
 private:
  inline void set_has_captcha_code();
  inline void clear_has_captcha_code();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* captcha_code_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_QQLoginCaptchaConfirm_2eproto();
  friend void protobuf_AssignDesc_QQLoginCaptchaConfirm_2eproto();
  friend void protobuf_ShutdownFile_QQLoginCaptchaConfirm_2eproto();

  void InitAsDefaultInstance();
  static QQLoginCaptchaConfirm* default_instance_;
};
// ===================================================================


// ===================================================================

// QQLoginCaptchaConfirm

// required string captcha_code = 1;
inline bool QQLoginCaptchaConfirm::has_captcha_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void QQLoginCaptchaConfirm::set_has_captcha_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void QQLoginCaptchaConfirm::clear_has_captcha_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void QQLoginCaptchaConfirm::clear_captcha_code() {
  if (captcha_code_ != &::google::protobuf::internal::kEmptyString) {
    captcha_code_->clear();
  }
  clear_has_captcha_code();
}
inline const ::std::string& QQLoginCaptchaConfirm::captcha_code() const {
  return *captcha_code_;
}
inline void QQLoginCaptchaConfirm::set_captcha_code(const ::std::string& value) {
  set_has_captcha_code();
  if (captcha_code_ == &::google::protobuf::internal::kEmptyString) {
    captcha_code_ = new ::std::string;
  }
  captcha_code_->assign(value);
}
inline void QQLoginCaptchaConfirm::set_captcha_code(const char* value) {
  set_has_captcha_code();
  if (captcha_code_ == &::google::protobuf::internal::kEmptyString) {
    captcha_code_ = new ::std::string;
  }
  captcha_code_->assign(value);
}
inline void QQLoginCaptchaConfirm::set_captcha_code(const char* value, size_t size) {
  set_has_captcha_code();
  if (captcha_code_ == &::google::protobuf::internal::kEmptyString) {
    captcha_code_ = new ::std::string;
  }
  captcha_code_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* QQLoginCaptchaConfirm::mutable_captcha_code() {
  set_has_captcha_code();
  if (captcha_code_ == &::google::protobuf::internal::kEmptyString) {
    captcha_code_ = new ::std::string;
  }
  return captcha_code_;
}
inline ::std::string* QQLoginCaptchaConfirm::release_captcha_code() {
  clear_has_captcha_code();
  if (captcha_code_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = captcha_code_;
    captcha_code_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void QQLoginCaptchaConfirm::set_allocated_captcha_code(::std::string* captcha_code) {
  if (captcha_code_ != &::google::protobuf::internal::kEmptyString) {
    delete captcha_code_;
  }
  if (captcha_code) {
    set_has_captcha_code();
    captcha_code_ = captcha_code;
  } else {
    clear_has_captcha_code();
    captcha_code_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_QQLoginCaptchaConfirm_2eproto__INCLUDED
