// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QQLoginCaptchaNotify.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "QQLoginCaptchaNotify.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

namespace {

const ::google::protobuf::Descriptor* QQLoginChaptchaNotify_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  QQLoginChaptchaNotify_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_QQLoginCaptchaNotify_2eproto() {
  protobuf_AddDesc_QQLoginCaptchaNotify_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "QQLoginCaptchaNotify.proto");
  GOOGLE_CHECK(file != NULL);
  QQLoginChaptchaNotify_descriptor_ = file->message_type(0);
  static const int QQLoginChaptchaNotify_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(QQLoginChaptchaNotify, captcha_data_),
  };
  QQLoginChaptchaNotify_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      QQLoginChaptchaNotify_descriptor_,
      QQLoginChaptchaNotify::default_instance_,
      QQLoginChaptchaNotify_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(QQLoginChaptchaNotify, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(QQLoginChaptchaNotify, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(QQLoginChaptchaNotify));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_QQLoginCaptchaNotify_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    QQLoginChaptchaNotify_descriptor_, &QQLoginChaptchaNotify::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_QQLoginCaptchaNotify_2eproto() {
  delete QQLoginChaptchaNotify::default_instance_;
  delete QQLoginChaptchaNotify_reflection_;
}

void protobuf_AddDesc_QQLoginCaptchaNotify_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::Protocol::protobuf_AddDesc_MessageBase_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\032QQLoginCaptchaNotify.proto\022\010Protocol\032\021"
    "MessageBase.proto\"-\n\025QQLoginChaptchaNoti"
    "fy\022\024\n\014captcha_data\030\001 \002(\014", 104);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "QQLoginCaptchaNotify.proto", &protobuf_RegisterTypes);
  QQLoginChaptchaNotify::default_instance_ = new QQLoginChaptchaNotify();
  QQLoginChaptchaNotify::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_QQLoginCaptchaNotify_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_QQLoginCaptchaNotify_2eproto {
  StaticDescriptorInitializer_QQLoginCaptchaNotify_2eproto() {
    protobuf_AddDesc_QQLoginCaptchaNotify_2eproto();
  }
} static_descriptor_initializer_QQLoginCaptchaNotify_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int QQLoginChaptchaNotify::kCaptchaDataFieldNumber;
#endif  // !_MSC_VER

QQLoginChaptchaNotify::QQLoginChaptchaNotify()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void QQLoginChaptchaNotify::InitAsDefaultInstance() {
}

QQLoginChaptchaNotify::QQLoginChaptchaNotify(const QQLoginChaptchaNotify& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void QQLoginChaptchaNotify::SharedCtor() {
  _cached_size_ = 0;
  captcha_data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

QQLoginChaptchaNotify::~QQLoginChaptchaNotify() {
  SharedDtor();
}

void QQLoginChaptchaNotify::SharedDtor() {
  if (captcha_data_ != &::google::protobuf::internal::kEmptyString) {
    delete captcha_data_;
  }
  if (this != default_instance_) {
  }
}

void QQLoginChaptchaNotify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* QQLoginChaptchaNotify::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return QQLoginChaptchaNotify_descriptor_;
}

const QQLoginChaptchaNotify& QQLoginChaptchaNotify::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_QQLoginCaptchaNotify_2eproto();
  return *default_instance_;
}

QQLoginChaptchaNotify* QQLoginChaptchaNotify::default_instance_ = NULL;

QQLoginChaptchaNotify* QQLoginChaptchaNotify::New() const {
  return new QQLoginChaptchaNotify;
}

void QQLoginChaptchaNotify::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_captcha_data()) {
      if (captcha_data_ != &::google::protobuf::internal::kEmptyString) {
        captcha_data_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool QQLoginChaptchaNotify::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bytes captcha_data = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_captcha_data()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void QQLoginChaptchaNotify::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required bytes captcha_data = 1;
  if (has_captcha_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      1, this->captcha_data(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* QQLoginChaptchaNotify::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required bytes captcha_data = 1;
  if (has_captcha_data()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->captcha_data(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int QQLoginChaptchaNotify::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bytes captcha_data = 1;
    if (has_captcha_data()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->captcha_data());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void QQLoginChaptchaNotify::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const QQLoginChaptchaNotify* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const QQLoginChaptchaNotify*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void QQLoginChaptchaNotify::MergeFrom(const QQLoginChaptchaNotify& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_captcha_data()) {
      set_captcha_data(from.captcha_data());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void QQLoginChaptchaNotify::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void QQLoginChaptchaNotify::CopyFrom(const QQLoginChaptchaNotify& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool QQLoginChaptchaNotify::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void QQLoginChaptchaNotify::Swap(QQLoginChaptchaNotify* other) {
  if (other != this) {
    std::swap(captcha_data_, other->captcha_data_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata QQLoginChaptchaNotify::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = QQLoginChaptchaNotify_descriptor_;
  metadata.reflection = QQLoginChaptchaNotify_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)
