// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotLoginRsp.proto

#ifndef PROTOBUF_RobotLoginRsp_2eproto__INCLUDED
#define PROTOBUF_RobotLoginRsp_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "MessageBase.pb.h"
// @@protoc_insertion_point(includes)

namespace Protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_RobotLoginRsp_2eproto();
void protobuf_AssignDesc_RobotLoginRsp_2eproto();
void protobuf_ShutdownFile_RobotLoginRsp_2eproto();

class RobotLoginRsp;

// ===================================================================

class RobotLoginRsp : public ::google::protobuf::Message {
 public:
  RobotLoginRsp();
  virtual ~RobotLoginRsp();

  RobotLoginRsp(const RobotLoginRsp& from);

  inline RobotLoginRsp& operator=(const RobotLoginRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RobotLoginRsp& default_instance();

  void Swap(RobotLoginRsp* other);

  // implements Message ----------------------------------------------

  RobotLoginRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RobotLoginRsp& from);
  void MergeFrom(const RobotLoginRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool login_result = 1;
  inline bool has_login_result() const;
  inline void clear_login_result();
  static const int kLoginResultFieldNumber = 1;
  inline bool login_result() const;
  inline void set_login_result(bool value);

  // @@protoc_insertion_point(class_scope:Protocol.RobotLoginRsp)
 private:
  inline void set_has_login_result();
  inline void clear_has_login_result();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  bool login_result_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_RobotLoginRsp_2eproto();
  friend void protobuf_AssignDesc_RobotLoginRsp_2eproto();
  friend void protobuf_ShutdownFile_RobotLoginRsp_2eproto();

  void InitAsDefaultInstance();
  static RobotLoginRsp* default_instance_;
};
// ===================================================================


// ===================================================================

// RobotLoginRsp

// required bool login_result = 1;
inline bool RobotLoginRsp::has_login_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RobotLoginRsp::set_has_login_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RobotLoginRsp::clear_has_login_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RobotLoginRsp::clear_login_result() {
  login_result_ = false;
  clear_has_login_result();
}
inline bool RobotLoginRsp::login_result() const {
  return login_result_;
}
inline void RobotLoginRsp::set_login_result(bool value) {
  set_has_login_result();
  login_result_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_RobotLoginRsp_2eproto__INCLUDED
