// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotLoginRsp.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "RobotLoginRsp.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

namespace {

const ::google::protobuf::Descriptor* RobotLoginRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RobotLoginRsp_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_RobotLoginRsp_2eproto() {
  protobuf_AddDesc_RobotLoginRsp_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "RobotLoginRsp.proto");
  GOOGLE_CHECK(file != NULL);
  RobotLoginRsp_descriptor_ = file->message_type(0);
  static const int RobotLoginRsp_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotLoginRsp, login_result_),
  };
  RobotLoginRsp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RobotLoginRsp_descriptor_,
      RobotLoginRsp::default_instance_,
      RobotLoginRsp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotLoginRsp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotLoginRsp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RobotLoginRsp));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_RobotLoginRsp_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RobotLoginRsp_descriptor_, &RobotLoginRsp::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_RobotLoginRsp_2eproto() {
  delete RobotLoginRsp::default_instance_;
  delete RobotLoginRsp_reflection_;
}

void protobuf_AddDesc_RobotLoginRsp_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::Protocol::protobuf_AddDesc_MessageBase_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023RobotLoginRsp.proto\022\010Protocol\032\021Message"
    "Base.proto\"%\n\rRobotLoginRsp\022\024\n\014login_res"
    "ult\030\001 \002(\010", 89);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "RobotLoginRsp.proto", &protobuf_RegisterTypes);
  RobotLoginRsp::default_instance_ = new RobotLoginRsp();
  RobotLoginRsp::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_RobotLoginRsp_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_RobotLoginRsp_2eproto {
  StaticDescriptorInitializer_RobotLoginRsp_2eproto() {
    protobuf_AddDesc_RobotLoginRsp_2eproto();
  }
} static_descriptor_initializer_RobotLoginRsp_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int RobotLoginRsp::kLoginResultFieldNumber;
#endif  // !_MSC_VER

RobotLoginRsp::RobotLoginRsp()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void RobotLoginRsp::InitAsDefaultInstance() {
}

RobotLoginRsp::RobotLoginRsp(const RobotLoginRsp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void RobotLoginRsp::SharedCtor() {
  _cached_size_ = 0;
  login_result_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RobotLoginRsp::~RobotLoginRsp() {
  SharedDtor();
}

void RobotLoginRsp::SharedDtor() {
  if (this != default_instance_) {
  }
}

void RobotLoginRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RobotLoginRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RobotLoginRsp_descriptor_;
}

const RobotLoginRsp& RobotLoginRsp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_RobotLoginRsp_2eproto();
  return *default_instance_;
}

RobotLoginRsp* RobotLoginRsp::default_instance_ = NULL;

RobotLoginRsp* RobotLoginRsp::New() const {
  return new RobotLoginRsp;
}

void RobotLoginRsp::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    login_result_ = false;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool RobotLoginRsp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bool login_result = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &login_result_)));
          set_has_login_result();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void RobotLoginRsp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required bool login_result = 1;
  if (has_login_result()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->login_result(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* RobotLoginRsp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required bool login_result = 1;
  if (has_login_result()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->login_result(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int RobotLoginRsp::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bool login_result = 1;
    if (has_login_result()) {
      total_size += 1 + 1;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RobotLoginRsp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const RobotLoginRsp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const RobotLoginRsp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void RobotLoginRsp::MergeFrom(const RobotLoginRsp& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_login_result()) {
      set_login_result(from.login_result());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void RobotLoginRsp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RobotLoginRsp::CopyFrom(const RobotLoginRsp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RobotLoginRsp::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void RobotLoginRsp::Swap(RobotLoginRsp* other) {
  if (other != this) {
    std::swap(login_result_, other->login_result_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata RobotLoginRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RobotLoginRsp_descriptor_;
  metadata.reflection = RobotLoginRsp_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)
