// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotLoginReq.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "RobotLoginReq.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

namespace {

const ::google::protobuf::Descriptor* RobotLoginReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RobotLoginReq_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_RobotLoginReq_2eproto() {
  protobuf_AddDesc_RobotLoginReq_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "RobotLoginReq.proto");
  GOOGLE_CHECK(file != NULL);
  RobotLoginReq_descriptor_ = file->message_type(0);
  static const int RobotLoginReq_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotLoginReq, verify_key_),
  };
  RobotLoginReq_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RobotLoginReq_descriptor_,
      RobotLoginReq::default_instance_,
      RobotLoginReq_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotLoginReq, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotLoginReq, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RobotLoginReq));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_RobotLoginReq_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RobotLoginReq_descriptor_, &RobotLoginReq::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_RobotLoginReq_2eproto() {
  delete RobotLoginReq::default_instance_;
  delete RobotLoginReq_reflection_;
}

void protobuf_AddDesc_RobotLoginReq_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::Protocol::protobuf_AddDesc_MessageBase_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023RobotLoginReq.proto\022\010Protocol\032\021Message"
    "Base.proto\"#\n\rRobotLoginReq\022\022\n\nverify_ke"
    "y\030\001 \002(\t", 87);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "RobotLoginReq.proto", &protobuf_RegisterTypes);
  RobotLoginReq::default_instance_ = new RobotLoginReq();
  RobotLoginReq::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_RobotLoginReq_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_RobotLoginReq_2eproto {
  StaticDescriptorInitializer_RobotLoginReq_2eproto() {
    protobuf_AddDesc_RobotLoginReq_2eproto();
  }
} static_descriptor_initializer_RobotLoginReq_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int RobotLoginReq::kVerifyKeyFieldNumber;
#endif  // !_MSC_VER

RobotLoginReq::RobotLoginReq()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void RobotLoginReq::InitAsDefaultInstance() {
}

RobotLoginReq::RobotLoginReq(const RobotLoginReq& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void RobotLoginReq::SharedCtor() {
  _cached_size_ = 0;
  verify_key_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RobotLoginReq::~RobotLoginReq() {
  SharedDtor();
}

void RobotLoginReq::SharedDtor() {
  if (verify_key_ != &::google::protobuf::internal::kEmptyString) {
    delete verify_key_;
  }
  if (this != default_instance_) {
  }
}

void RobotLoginReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RobotLoginReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RobotLoginReq_descriptor_;
}

const RobotLoginReq& RobotLoginReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_RobotLoginReq_2eproto();
  return *default_instance_;
}

RobotLoginReq* RobotLoginReq::default_instance_ = NULL;

RobotLoginReq* RobotLoginReq::New() const {
  return new RobotLoginReq;
}

void RobotLoginReq::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_verify_key()) {
      if (verify_key_ != &::google::protobuf::internal::kEmptyString) {
        verify_key_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool RobotLoginReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string verify_key = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_verify_key()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->verify_key().data(), this->verify_key().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void RobotLoginReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string verify_key = 1;
  if (has_verify_key()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->verify_key().data(), this->verify_key().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->verify_key(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* RobotLoginReq::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string verify_key = 1;
  if (has_verify_key()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->verify_key().data(), this->verify_key().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->verify_key(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int RobotLoginReq::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string verify_key = 1;
    if (has_verify_key()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->verify_key());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RobotLoginReq::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const RobotLoginReq* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const RobotLoginReq*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void RobotLoginReq::MergeFrom(const RobotLoginReq& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_verify_key()) {
      set_verify_key(from.verify_key());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void RobotLoginReq::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RobotLoginReq::CopyFrom(const RobotLoginReq& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RobotLoginReq::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void RobotLoginReq::Swap(RobotLoginReq* other) {
  if (other != this) {
    std::swap(verify_key_, other->verify_key_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata RobotLoginReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RobotLoginReq_descriptor_;
  metadata.reflection = RobotLoginReq_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)
