//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: 20002_C2SQQLoginCaptchaConfirm.proto
namespace Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SQQLoginCaptchaConfirm")]
  public partial class C2SQQLoginCaptchaConfirm : global::ProtoBuf.IExtensible
  {
    public C2SQQLoginCaptchaConfirm() {}
    
    private string _captcha_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"captcha_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string captcha_code
    {
      get { return _captcha_code; }
      set { _captcha_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}