//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: QQLoginCaptchaNotify.proto
// Note: requires additional types generated from: MessageBase.proto
namespace Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QQLoginChaptchaRsp")]
  public partial class QQLoginChaptchaRsp : global::ProtoBuf.IExtensible
  {
    public QQLoginChaptchaRsp() {}
    
    private byte[] _captcha_data;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"captcha_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] captcha_data
    {
      get { return _captcha_data; }
      set { _captcha_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}