//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RobotLoginReq.proto
// Note: requires additional types generated from: MessageBase.proto
namespace Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RobotLoginReq")]
  public partial class RobotLoginReq : global::ProtoBuf.IExtensible
  {
    public RobotLoginReq() {}
    
    private string _verify_key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"verify_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string verify_key
    {
      get { return _verify_key; }
      set { _verify_key = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}