//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RobotLoginRsp.proto
// Note: requires additional types generated from: MessageBase.proto
namespace Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RobotLoginRsp")]
  public partial class RobotLoginRsp : global::ProtoBuf.IExtensible
  {
    public RobotLoginRsp() {}
    
    private bool _login_result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"login_result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool login_result
    {
      get { return _login_result; }
      set { _login_result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}